name: denis
favicon: null
layout_spectrum: 0.5483417275827378
typography_spectrum: 0.941554406657815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9786999067291617
  lightness: 0.02441779267974198
  saturation: 0.39106024778448045
  rhythmicContrast: 0.7045080149546266
purpose: []
